import pandas as pd
import numpy as np

def limpiar_datos_venture(dff):
    df = dff.copy()
    # Standarize columns names
    df.columns = map(str.lower, df.columns)
    df.columns = [label.replace(' ', '_') for label in df.columns]
    df.columns = [label.replace('%', 'pr') for label in df.columns]

    # Limpiar registros no encontrados
    if 'pbid' in df.columns:   
        df_drop_me = (df['pbid'] == "#NOMATCH")
        df = df.drop(df[df_drop_me].index)
        col_names = ['pbid']
        df = df.drop(col_names, axis=1)
        del df_drop_me


    # Stadarize no data wit nan
    def clean_no_data(value):
        """Remplaza todos los 'No data' por np.nan."""
        label = np.nan if (value == 'No data') else value
        return label

    for cols in (df.columns):
        df[cols] = df[cols].apply(clean_no_data)


    # Format number columns
    num_cols = ['year_founded',
                'most_recent_post_valuation',
                'employees',
                'most_recent_raised_to_date',
                'most_recent_deal_size',
                'last_known_valuation',
                'biography',
                'active_investors_names',
                'lead_partners_on_deals_count',
                'professionals_count',
                'deals_count',
                'most_recent_pr_acquired',
                'subsidiary_companies_count'           
               ]
  
    
    for cols in num_cols:
        df[cols] = pd.to_numeric(df[cols]).round(4)

        
    # Delete wrong data inputs
    df = df[df['year_founded'] >= 2010]
    df = df[df['startup'] != "Meit!"]    

    
    # Categories standarization
    # Series
    rename_dict_series = {'Later Stage VC':'Pre-IPO',
                    'Early Stage VC':'Pre-Seed',
                    'Accelerator/Incubator':'Pre-Seed',
                    'PIPE':'Exit',
                    'Merger/Acquisition':'Exit',
                    'Secondary Transaction - Private':'Exit',
                    'Seed Round':'Seed',
                    'Series B':'Series B',
                    'Debt - General':'Other',
                    'IPO':'Pre-IPO',
                    'PE Growth/Expansion':'Pre-IPO',
                    'Out of Business':'Out of Business',
                    'Series A':'Series A',
                    'Corporate':'Pre-IPO',
                    'Debt - PPP':'Other',
                    'Angel (individual)':'Pre-Seed',
                    'Series D':'Series C+',
                    'Series B1':'Series B',
                    'Public Investment 2nd Offering':'Exit',
                    'Series 1':'Pre-Seed',
                    'Series C':'Series C+',
                    'Series A1':'Series A',
                    'Series A2':'Series A',
                    'Series E':'Series C+',
                    'Add-on':'Other',
                    'Dividend Recapitalization':'Other',
                    'Add-on':'Other',
                    'Dividend Recapitalization':'Other',
                    'Equity Crowdfunding':'Other',
                    'Grant':'Other',
                    'Mezzanine':'Other',
                    'Pre-Seed':'Pre-Seed',
                    'Secondary Transaction - Open Market':'Exit',
                    'Seed':'Serie Seed',
                    'Series 2':'Serie Seed',
                    'Series A':'Series A',
                    'Series A1':'Series A',
                    'Series B':'Series B',
                    'Series B2':'Series B',
                    'Series C+':'Series C+',
                    'Series F':'Series C+',
                    'Series G':'Series C+',
                    'Acquisition Financing':'Exit',
                    'Bankruptcy: Liquidation':'Out of Business',
                    'Corporate Divestiture':'Exit',
                    'Merger of Equals':'Exit',
                    'Recapitalization':'Other',
                    'Sale-Lease back facility':'Other',
                    'Secondary Buyout':'Exit',
                    'Secondary Transaction - Stock Distribution':'Exit',
                    'Series D2':'Series C+',
                  }

    # Countires
    rename_dict_country = { 'United States':'USA',
                    'Singapore':'Singapore',
                    'United Kingdom':'UK',
                    'Belgium':'Other',
                    'Latvia':'Other',
                    'Mexico':'Latam',
                    'Lithuania':'Other',
                    'Chile':'Latam',
                    'Australia':'Other',
                    'Colombia':'Latam',
                    'Argentina':'Latam',
                    'Canada':'Canada',
                    'Israel':'Israel',
                    'China':'Other',
                    'Taiwan':'Other',
                    'No data':'Other',
                    'Brazil':'Latam',
                    'India':'India',
                    'Indonesia':'Other',
                    'Spain':'Other',
                    'New Zealand':'Other',
                    'Sweden':'EU',
                    'Japan':'Other',
                    'Poland':'Other',
                    'Ecuador':'Latam',
                    'El Salvador':'Latam',
                    'Finland':'Other',
                    'France':'EU',
                    'Germany':'EU',
                    'Gibraltar':'Other',
                    'Iran':'Other',
                    'Ireland':'UK',
                    'Kenya':'Other',
                    'Netherlands':'EU',
                    'Nigeria':'Other',
                    'Norway':'Other',
                    'Panama':'Other',
                    'Peru':'Latam',
                    'Russia':'Latam',
                    'South Korea':'Other',
                    'Switzerland':'Other',
                    'Austria':'Other',
                    'Bahrain':'Other',
                    'Bangladesh':'Other',
                    'Bolivia':'Latam',
                    'Bulgaria':'Other',
                    'Costa Rica':'Other',
                    'Denmark':'EU',
                    'Dominican Republic':'Other',
                    'Egypt':'Other',
                    'Georgia':'Other',
                    'Guatemala':'Latam',
                    'Hong Kong':'Other',
                    'Luxembourg':'EU',
                    'Mauritius':'Other',
                    'Pakistan':'Other',
                    'Portugal':'EU',
                    'Romania':'Other',
                    'Uganda':'Other',
                    'United Arab Emirates':'Other',
                    'Vietnam':'Other',
                    'Zambia':'Other'
                  }

    rename_dict_industry = {
                    'Financial Software':'Fintech',
                    'Electrical Equipment':'Mobility',
                    'Business/Productivity Software':'Healthtech',
                    'Property and Casualty Insurance':'Fintech',
                    'Media and Information Services (B2B)':'Retail',
                    'Financial Software':'Mobility',
                    'Business/Productivity Software':'Retail',
                    'Practice Management (Healthcare)':'Others',
                    'Business/Productivity Software':'Mobility',
                    'Electric Utilities':'Others',
                    'Education and Training Services (B2B)':'Others',
                    'Educational and Training Services (B2C)':'Healthtech',
                    'Specialty Retail':'Agtech',
                    'Other Communications and Networking':'Mobility',
                    'Clinics/Outpatient Services':'Healthtech',
                    'Other Financial Services':'Fintech',
                    'Consumer Finance':'Fintech',
                    'Specialized Finance':'Fintech',
                    'Internet Retail':'Retail',
                    'Educational and Training Services (B2C)':'Others',
                    'Other Restaurants, Hotels and Leisure':'Mobility',
                    'Other Services (B2C Non-Financial)':'Retail',
                    'Information Services (B2C)':'Retail',
                    'Database Software':'Fintech',
                    'Business/Productivity Software':'Others',
                    'Cultivation':'Others',
                    'Other Devices and Supplies':'Mobility',
                    'Educational Software':'Others',
                    'Media and Information Services (B2B)':'Deeptech',
                    'Other Services (B2C Non-Financial)':'Others',
                    'Financial Software':'Retail',
                    'Real Estate Services (B2C)':'Fintech',
                    'Business/Productivity Software':'Deeptech',
                    'Electronic Equipment and Instruments':'Deeptech',
                    'Asset Management':'Fintech',
                    'Communication Software':'Others',
                    'Electronic Equipment and Instruments':'Others',
                    'Information Services (B2C)':'Fintech',
                    'Other Healthcare Services':'Healthtech',
                    'Network Management Software':'Others',
                    'Other Services (B2C Non-Financial)':'Mundo B2B',
                    'Real Estate Services (B2C)':'Proptech',
                    'Application Software':'Fintech',
                    'Automotive Insurance':'Deeptech',
                    'Other Hardware':'Retail',
                    'Media and Information Services (B2B)':'Others',
                    'Other Healthcare Technology Systems':'Healthtech',
                    'Network Management Software':'Deeptech',
                    'Drug Discovery':'Proptech',
                    'Business/Productivity Software':'Fintech',
                    'Human Capital Services':'Mundo B2B',
                    'Other Services (B2C Non-Financial)':'Mobility',
                    'Automotive':'Mobility',
                    'Logistics':'Mobility',
                    'Food Products':'Healthtech',
                    'Financial Software':'Mundo B2B',
                    'Private Equity':'Deeptech',
                    'Financial Software':'Insuretech',
                    'Internet Software':'Mundo B2B',
                    'Media and Information Services (B2B)':'Proptech',
                    'Database Software':'Others',
                    'Other Restaurants, Hotels and Leisure':'Retail',
                    'IT Consulting and Outsourcing':'Retail',
                    'Other Services (B2C Non-Financial)':'Healthtech',
                    'Outcome Management (Healthcare)':'Healthtech',
                    'Automotive Insurance':'Fintech',
                    'Automotive':'Retail',
                    'Business/Productivity Software':'Mundo B2B',
                    'Specialty Retail':'Retail',
                    'Media and Information Services (B2B)':'Fintech',
                    'Clinics/Outpatient Services':'Proptech',
                    'Other Financial Services':'Proptech',
                    'Media and Information Services (B2B)':'Agtech',
                    'Specialized Finance':'Others',
                    'Life and Health Insurance':'Retail',
                    'Entertainment Software':'Proptech',
                    'Business/Productivity Software':'Agtech',
                    'Clinics/Outpatient Services':'Mobility',
                    'Other Financial Services':'Mobility',
                    'Other Hardware':'Fintech',
                    'Biotechnology':'Retail',
                    'Media and Information Services (B2B)':'Healthtech',
                    'Automotive Insurance':'Retail',
                    'Communication Software':'Healthtech',
                    'Enterprise Systems (Healthcare)':'Fintech',
                    'Logistics':'Retail',
                    'Network Management Software':'Mundo B2B',
                    'Business/Productivity Software':'Proptech',
                    'Office Services (B2B)':'Mobility',
                    'Other Services (B2C Non-Financial)':'Agtech',
                    'Machinery (B2B)':'Others',
                    'Internet Retail':'Others',
                    'Social/Platform Software':'Others',
                    'Personal Products':'Agtech',
                    'Environmental Services (B2B)':'Others',
                    'Electronic Equipment and Instruments':'Mobility',
                    'Educational Software':'Retail',
                    'General Purpose Semiconductors':'Fintech',
                    'Other Capital Markets/Institutions':'Retail',
                    'Food Products':'Agtech',
                    'Energy Marketing':'Agtech',
                    'Logistics':'Others',
                    'Financial Software':'Proptech',
                    'Electronics (B2C)':'Others',
                    'Application Software':'Retail',
                    'Personal Products':'Others',
                    'Other Commercial Products':'Retail',
                    'Database Software':'Mundo B2B',
                    'Regional Banks':'Agtech',
                    'Aerospace and Defense':'Mobility',
                    'Animal Husbandry':'Agtech',
                    'Communication Software':'Fintech',
                    'Electronic Equipment and Instruments':'Agtech',
                    'Financial Software':'Others',
                    'Other Restaurants, Hotels and Leisure':'Healthtech',
                    'Media and Information Services (B2B)':'Mobility',
                    'Therapeutic Devices':'Healthtech',
                    'Multimedia and Design Software':'Mobility',
                    'Laboratory Services (Healthcare)':'Healthtech',
                    'Internet Retail':'Healthtech',
                    'Software Development Applications':'Fintech',
                    'Machinery (B2B)':'Retail',
                    'Clinics/Outpatient Services':'Fintech',
                    'Financial Software':'Healthtech',
                    'Social/Platform Software':'Retail',
                    'Decision/Risk Analysis':'Healthtech',
                    'Media and Information Services (B2B)':'Mundo B2B',
                    'Application Specific Semiconductors':'Mobility',
                    'Diagnostic Equipment':'Healthtech',
                    'Marine':'Retail',
                    'Other Insurance':'Insuretech',
                    'Biotechnology':'Insuretech',
                    'Automotive':'Insuretech',
                    'Other Healthcare Technology Systems':'Insuretech',
                    'Communication Software':'Insuretech',
                    'Property and Casualty Insurance':'Insuretech',
                    'Elder and Disabled Care':'Insuretech',
                    'Business/Productivity Software':'Insuretech',
                    'Life and Health Insurance':'Insuretech',
                    'Insurance Brokers':'Insuretech',
                    'Logistics':'Deeptech',
                    'Life and Health Insurance':'Fintech',
                    'Energy Exploration':'Deeptech',
                    'Medical Records Systems':'Fintech',
                    'Real Estate Services (B2C)':'Mobility',
                    'Internet Software':'Deeptech',
                    'Energy Storage':'Mundo B2B',
                    'Medical Records Systems':'Healthtech',
                    'Software Development Applications':'Mobility',
                    'Software Development Applications':'Deeptech',
                    'Personal Products':'Retail',
                    'Communication Software':'Mundo B2B',
                    'Logistics':'Mundo B2B',
                    'Food Products':'Retail',
                    'Environmental Services (B2B)':'Deeptech',
                    'Business/Productivity Software':'Others',
                    'Social/Platform Software':'Fintech',
                    'Automation/Workflow Software':'Deeptech',
                    'Multimedia and Design Software':'Mundo B2B',
                    'Enterprise Systems (Healthcare)':'Healthtech',
                    'Special Purpose Acquisition Company (SPAC)':'Mundo B2B',
                    'Holding Companies':'Retail',
                    'Systems and Information Management':'Smart Cities',
                    'Environmental Services (B2B)':'Smart Cities',
                    'Business/Productivity Software':'Smart Cities',
                    'Other Commercial Services':'Healthtech',
                    'Educational Software':'Fintech',
                    'Business/Productivity Software':'Energy',
                    'Real Estate Services (B2C)':'Mundo B2B',
                    'Wireless Communications Equipment':'Smart Cities',
                    'Application Software':'Mundo B2B',
                    'Accounting, Audit and Tax Services (B2B)':'Mundo B2B',
                    'Internet Retail':'Mundo B2B',
                    'Social/Platform Software':'Mundo B2B',
                    'Other Media':'Others',
                    'Drug Delivery':'Healthtech',
                    'Alternative Energy Equipment':'Energy',
                    'Multi-line Insurance':'Insuretech',
                    'Network Management Software':'Mobility',
                    'IT Consulting and Outsourcing':'Mobility',
                    'Other Hardware':'Mobility',
                    'Road':'Mobility',
                    'Other Agriculture':'Agtech',
                    'Human Capital Services':'Fintech',
                    'Entertainment Software':'Fintech',
                    'Social/Platform Software':'Mobility',
                    'Database Software':'Mobility',
                    'Logistics':'Fintech',
                    'Application Software':'Healthtech',
                    'Electronics (B2C)':'Energy',
                    'Other Hardware':'Agtech',
                    'Pharmaceuticals':'Retail',
                    'Educational and Training Services (B2C)':'Mundo B2B',
                    'Network Management Software':'Retail',
                    'Other Services (B2C Non-Financial)':'Insuretech',
                    'Air':'Others',
                    'Human Capital Services':'Retail',
                    'Consulting Services (B2B)':'Retail',
                    'Communication Software':'Proptech',
                    'Information Services (B2C)':'Proptech',
                    'Elder and Disabled Care':'Healthtech',
                    'Automotive Insurance':'Mobility',
                    'Monitoring Equipment':'Healthtech',
                    'Other Commercial Banks':'Fintech',
                    'IT Consulting and Outsourcing':'Fintech',
                    'Electronic Equipment and Instruments':'Proptech',
                    'Systems and Information Management':'Mundo B2B',
                    'Network Management Software':'Fintech',
                    'Distributors (Healthcare)':'Retail',
                    'Consumer Finance':'Agtech',
                    'IT Consulting and Outsourcing':'Agtech',
                    'Multimedia and Design Software':'Proptech',
                    'Drug Discovery':'Healthtech',
                    'Automotive Insurance':'Insuretech',
                    'Construction and Engineering':'Proptech',
                    'Specialty Retail':'Fintech',
                    'Environmental Services (B2B)':'Fintech',
                    'Home Furnishings':'Proptech',
                    'Environmental Services (B2B)':'Energy',
                    'Monitoring Equipment':'Mobility',
                    'Information Services (B2C)':'Mundo B2B',
                    'Other Energy Services':'Smart Cities',
                    'Food Products':'Mundo B2B',
                    'Other Financial Services':'Retail',
                    'Building Products':'Proptech',
                    'Clinics/Outpatient Services':'Mundo B2B',
                    'Financial Software':'Deeptech',
                    'Other Services (B2C Non-Financial)':'Fintech',
                    'Aerospace and Defense':'Healthtech',
                    'Specialized Finance':'Mobility',
                    'IT Consulting and Outsourcing':'Others',
                    'Private Equity':'Others',
                    'Other Hardware':'Others',
                    'Monitoring Equipment':'Healthtech',
                    'Energy Production':'Energy',
                    'Software Development Applications':'Mundo B2B',
                    'Network Management Software':'Agtech',
                    'Other Restaurants, Hotels and Leisure':'Mundo B2B',
                    'Brokerage':'Proptech',
                    'Other Capital Markets/Institutions':'Mundo B2B',
                    'General Purpose Semiconductors':'Retail',
                    'Life and Health Insurance':'Deeptech',
                    'Brokerage':'Fintech',
                    'Other Healthcare Technology Systems':'Mundo B2B',
                    'Drug Discovery':'Mundo B2B',
                    'Human Capital Services':'Others',
                    'Electronics (B2C)':'Deeptech',
                    'Legal Services (B2B)':'Others',
                    'Electronic Equipment and Instruments':'Energy',
                    'Social Content':'Retail',
                    'Application Software':'Deeptech',
                    'Enterprise Systems (Healthcare)':'Retail',
                    'Biotechnology':'Energy',
                    'Personal Products':'Deeptech',
                    'Database Software':'Deeptech',
                    'Other Services (B2C Non-Financial)':'Energy',
                    'Internet Retail':'Deeptech',
                    'Automation/Workflow Software':'Fintech',
                    'Automotive':'Fintech',
                    'Education and Training Services (B2B)':'Retail',
                    'Financial Software':'Energy',
                    'Entertainment Software':'Others',
                    'Social/Platform Software':'Deeptech',
                    'Brokerage':'Mundo B2B',
                    'Other Hardware':'Mundo B2B',
                    'Other Devices and Supplies':'Retail',
                    'Other Commercial Services':'Retail',
                    'Marine':'Mobility',
                    'Educational and Training Services (B2C)':'Retail',
                    'Human Capital Services':'Healthtech',
                    'Communication Software':'Deeptech',
                    'National Banks':'Fintech',
                    'Road':'Mundo B2B',
                    'Software Development Applications':'Others',
                    'Medical Supplies':'Healthtech',
                    'Biotechnology':'Healthtech',
                    'Enterprise Systems (Healthcare)':'Mundo B2B',
                    'Aerospace and Defense':'Deeptech',
                    'Other Financial Services':'Deeptech',
                    'Entertainment Software':'Healthtech',
                    'Aerospace and Defense':'Energy',
                    'Clothing':'Deeptech',
                    'Specialty Chemicals':'Mobility',
                    'Clothing':'Proptech',
                    'Personal Products':'Proptech',
                    'Electronics (B2C)':'Healthtech',
                    'Special Purpose Acquisition Company (SPAC)':'Healthtech',
                    'Entertainment Software':'Retail',
                    'Other Hardware':'Deeptech',
                    'IT Consulting and Outsourcing':'Mundo B2B',
                    'Educational Software':'Mundo B2B',
                    'Surgical Devices':'Mundo B2B',
                    'Biotechnology':'Mundo B2B',
                    'Other Commercial Services':'Mundo B2B',
                    'Multi-line Insurance':'Mobility',
                    'Media and Information Services (B2B)':'Others',
                    'Human Capital Services':'Insuretech',
                    'Restaurants and Bars':'Retail',
                    'Specialty Retail':'Mundo B2B',
                    'Home Furnishings':'Mundo B2B',
                    'Systems and Information Management':'Fintech',
                    'Application Software':'Others',
                    'Holding Companies':'Mundo B2B',
                    'Consumer Finance':'Mobility',
                    'Paper Containers and Packaging':'Retail',
                    'Leisure Facilities':'Retail',
                    'Clothing':'Retail',
                    'Environmental Services (B2B)':'Mundo B2B'
                  }


    # Format transofrmation
    df["most_recent_deal_type_2"] = df["most_recent_deal_type_2"].replace(rename_dict_series).astype("category")
    df["country"] = df["hq_country"].replace(rename_dict_country).astype("category")
    df["business_status"] = df["business_status"].astype("category")
    df["primary_industry_code"] = df["primary_industry_code"].replace(rename_dict_industry).astype("category")

    # 2. Feature Engineering & EDA

    # Lenght of string features
    #df['brief_description'] = pd.to_numeric(df['brief_description'].str.len())

    # Startup age
    df['year_founded'] = pd.to_numeric(df['year_founded'])
    
    # Normalized dataframe
    
    df_norm = df.copy()
    
    for feature_name in df_norm.columns:     
        if feature_name not in list(df_norm.select_dtypes(['category','object']).columns):
            # Normalize
            df_norm[feature_name] = df_norm[feature_name].astype(np.float64)
            max_val = df_norm[feature_name].max()
            min_val = df_norm[feature_name].min()
            df_norm[feature_name] = (df_norm[feature_name] - min_val) / (max_val - min_val)
            # Fill na with mean
            df_norm[feature_name] = df_norm[feature_name].fillna(df_norm[feature_name].mean())
        else:
            df_norm[feature_name] = df_norm[feature_name]
        
    return df, df_norm

def clean_to_predict(test, df_no_norm):
    
    df = pd.DataFrame(test, columns = df_no_norm.columns)
    # Standarize columns names
    df.columns = map(str.lower, df.columns)
    df.columns = [label.replace(' ', '_') for label in df.columns]
    
        # Stadarize no data wit nan
    def clean_no_data(value):
        """Remplaza todos los 'No data' y None por np.nan."""
        label = np.nan if (value == 'No data' or value == None) else value
        return label

    for cols in (df.columns):
        df[cols] = df[cols].apply(clean_no_data)


    # Format number columns
    num_cols = ['year_founded',
                'most_recent_post_valuation',
                'employees',
                'most_recent_raised_to_date',
                'most_recent_deal_size',
                'last_known_valuation',
                'biography',
                'active_investors_names',
                'lead_partners_on_deals_count',
                'professionals_count',
                'deals_count',
                'most_recent_pr_acquired',
                'subsidiary_companies_count'           
               ]
    
    for cols in num_cols:
        df[cols] = pd.to_numeric(df[cols]).round(4)

        
    # Delete wrong data inputs
    df = df[df['year_founded'] >= 2010]
    df = df[df['startup'] != "Meit!"]    

    
    # Categories standarization
    # Series
    rename_dict1 = {'Later Stage VC':'Pre-IPO',
                    'Early Stage VC':'Pre-Seed',
                    'Accelerator/Incubator':'Pre-Seed',
                    'PIPE':'Exit',
                    'Merger/Acquisition':'Exit',
                    'Secondary Transaction - Private':'Exit',
                    'Seed Round':'Seed',
                    'Series B':'Series B',
                    'Debt - General':'Other',
                    'IPO':'Pre-IPO',
                    'PE Growth/Expansion':'Pre-IPO',
                    'Out of Business':'Out of Business',
                    'Series A':'Series A',
                    'Corporate':'Pre-IPO',
                    'Debt - PPP':'Other',
                    'Angel (individual)':'Pre-Seed',
                    'Series D':'Series C+',
                    'Series B1':'Series B',
                    'Public Investment 2nd Offering':'Exit',
                    'Series 1':'Pre-Seed',
                    'Series C':'Series C+',
                    'Series A1':'Series A',
                    'Series A2':'Series A',
                    'Series E':'Series C+',
                    'Add-on':'Other',
                    'Dividend Recapitalization':'Other',
                    'Add-on':'Other',
                    'Dividend Recapitalization':'Other',
                    'Equity Crowdfunding':'Other',
                    'Grant':'Other',
                    'Mezzanine':'Other',
                    'Pre-Seed':'Pre-Seed',
                    'Secondary Transaction - Open Market':'Exit',
                    'Seed':'Serie Seed',
                    'Series 2':'Serie Seed',
                    'Series A':'Series A',
                    'Series A1':'Series A',
                    'Series B':'Series B',
                    'Series B2':'Series B',
                    'Series C+':'Series C+',
                    'Series F':'Series C+',
                    'Series G':'Series C+',
                    'Acquisition Financing':'Exit',
                    'Bankruptcy: Liquidation':'Out of Business',
                    'Corporate Divestiture':'Exit',
                    'Merger of Equals':'Exit',
                    'Recapitalization':'Other',
                    'Sale-Lease back facility':'Other',
                    'Secondary Buyout':'Exit',
                    'Secondary Transaction - Stock Distribution':'Exit',
                    'Series D2':'Series C+',
                  }

    # Countires
    rename_dict2 = { 'United States':'USA',
                    'Singapore':'Singapore',
                    'United Kingdom':'UK',
                    'Belgium':'Other',
                    'Latvia':'Other',
                    'Mexico':'Latam',
                    'Lithuania':'Other',
                    'Chile':'Latam',
                    'Australia':'Other',
                    'Colombia':'Latam',
                    'Argentina':'Latam',
                    'Canada':'Canada',
                    'Israel':'Israel',
                    'China':'Other',
                    'Taiwan':'Other',
                    'No data':'Other',
                    'Brazil':'Latam',
                    'India':'India',
                    'Indonesia':'Other',
                    'Spain':'Other',
                    'New Zealand':'Other',
                    'Sweden':'EU',
                    'Japan':'Other',
                    'Poland':'Other',
                    'Ecuador':'Latam',
                    'El Salvador':'Latam',
                    'Finland':'Other',
                    'France':'EU',
                    'Germany':'EU',
                    'Gibraltar':'Other',
                    'Iran':'Other',
                    'Ireland':'UK',
                    'Kenya':'Other',
                    'Netherlands':'EU',
                    'Nigeria':'Other',
                    'Norway':'Other',
                    'Panama':'Other',
                    'Peru':'Latam',
                    'Russia':'Latam',
                    'South Korea':'Other',
                    'Switzerland':'Other',
                    'Austria':'Other',
                    'Bahrain':'Other',
                    'Bangladesh':'Other',
                    'Bolivia':'Latam',
                    'Bulgaria':'Other',
                    'Costa Rica':'Other',
                    'Denmark':'EU',
                    'Dominican Republic':'Other',
                    'Egypt':'Other',
                    'Georgia':'Other',
                    'Guatemala':'Latam',
                    'Hong Kong':'Other',
                    'Luxembourg':'EU',
                    'Mauritius':'Other',
                    'Pakistan':'Other',
                    'Portugal':'EU',
                    'Romania':'Other',
                    'Uganda':'Other',
                    'United Arab Emirates':'Other',
                    'Vietnam':'Other',
                    'Zambia':'Other'
                  }

    rename_dict3 = {
                    'Financial Software':'Fintech',
                    'Electrical Equipment':'Mobility',
                    'Business/Productivity Software':'Healthtech',
                    'Property and Casualty Insurance':'Fintech',
                    'Media and Information Services (B2B)':'Retail',
                    'Financial Software':'Mobility',
                    'Business/Productivity Software':'Retail',
                    'Practice Management (Healthcare)':'Others',
                    'Business/Productivity Software':'Mobility',
                    'Electric Utilities':'Others',
                    'Education and Training Services (B2B)':'Others',
                    'Educational and Training Services (B2C)':'Healthtech',
                    'Specialty Retail':'Agtech',
                    'Other Communications and Networking':'Mobility',
                    'Clinics/Outpatient Services':'Healthtech',
                    'Other Financial Services':'Fintech',
                    'Consumer Finance':'Fintech',
                    'Specialized Finance':'Fintech',
                    'Internet Retail':'Retail',
                    'Educational and Training Services (B2C)':'Others',
                    'Other Restaurants, Hotels and Leisure':'Mobility',
                    'Other Services (B2C Non-Financial)':'Retail',
                    'Information Services (B2C)':'Retail',
                    'Database Software':'Fintech',
                    'Business/Productivity Software':'Others',
                    'Cultivation':'Others',
                    'Other Devices and Supplies':'Mobility',
                    'Educational Software':'Others',
                    'Media and Information Services (B2B)':'Deeptech',
                    'Other Services (B2C Non-Financial)':'Others',
                    'Financial Software':'Retail',
                    'Real Estate Services (B2C)':'Fintech',
                    'Business/Productivity Software':'Deeptech',
                    'Electronic Equipment and Instruments':'Deeptech',
                    'Asset Management':'Fintech',
                    'Communication Software':'Others',
                    'Electronic Equipment and Instruments':'Others',
                    'Information Services (B2C)':'Fintech',
                    'Other Healthcare Services':'Healthtech',
                    'Network Management Software':'Others',
                    'Other Services (B2C Non-Financial)':'Mundo B2B',
                    'Real Estate Services (B2C)':'Proptech',
                    'Application Software':'Fintech',
                    'Automotive Insurance':'Deeptech',
                    'Other Hardware':'Retail',
                    'Media and Information Services (B2B)':'Others',
                    'Other Healthcare Technology Systems':'Healthtech',
                    'Network Management Software':'Deeptech',
                    'Drug Discovery':'Proptech',
                    'Business/Productivity Software':'Fintech',
                    'Human Capital Services':'Mundo B2B',
                    'Other Services (B2C Non-Financial)':'Mobility',
                    'Automotive':'Mobility',
                    'Logistics':'Mobility',
                    'Food Products':'Healthtech',
                    'Financial Software':'Mundo B2B',
                    'Private Equity':'Deeptech',
                    'Financial Software':'Insuretech',
                    'Internet Software':'Mundo B2B',
                    'Media and Information Services (B2B)':'Proptech',
                    'Database Software':'Others',
                    'Other Restaurants, Hotels and Leisure':'Retail',
                    'IT Consulting and Outsourcing':'Retail',
                    'Other Services (B2C Non-Financial)':'Healthtech',
                    'Outcome Management (Healthcare)':'Healthtech',
                    'Automotive Insurance':'Fintech',
                    'Automotive':'Retail',
                    'Business/Productivity Software':'Mundo B2B',
                    'Specialty Retail':'Retail',
                    'Media and Information Services (B2B)':'Fintech',
                    'Clinics/Outpatient Services':'Proptech',
                    'Other Financial Services':'Proptech',
                    'Media and Information Services (B2B)':'Agtech',
                    'Specialized Finance':'Others',
                    'Life and Health Insurance':'Retail',
                    'Entertainment Software':'Proptech',
                    'Business/Productivity Software':'Agtech',
                    'Clinics/Outpatient Services':'Mobility',
                    'Other Financial Services':'Mobility',
                    'Other Hardware':'Fintech',
                    'Biotechnology':'Retail',
                    'Media and Information Services (B2B)':'Healthtech',
                    'Automotive Insurance':'Retail',
                    'Communication Software':'Healthtech',
                    'Enterprise Systems (Healthcare)':'Fintech',
                    'Logistics':'Retail',
                    'Network Management Software':'Mundo B2B',
                    'Business/Productivity Software':'Proptech',
                    'Office Services (B2B)':'Mobility',
                    'Other Services (B2C Non-Financial)':'Agtech',
                    'Machinery (B2B)':'Others',
                    'Internet Retail':'Others',
                    'Social/Platform Software':'Others',
                    'Personal Products':'Agtech',
                    'Environmental Services (B2B)':'Others',
                    'Electronic Equipment and Instruments':'Mobility',
                    'Educational Software':'Retail',
                    'General Purpose Semiconductors':'Fintech',
                    'Other Capital Markets/Institutions':'Retail',
                    'Food Products':'Agtech',
                    'Energy Marketing':'Agtech',
                    'Logistics':'Others',
                    'Financial Software':'Proptech',
                    'Electronics (B2C)':'Others',
                    'Application Software':'Retail',
                    'Personal Products':'Others',
                    'Other Commercial Products':'Retail',
                    'Database Software':'Mundo B2B',
                    'Regional Banks':'Agtech',
                    'Aerospace and Defense':'Mobility',
                    'Animal Husbandry':'Agtech',
                    'Communication Software':'Fintech',
                    'Electronic Equipment and Instruments':'Agtech',
                    'Financial Software':'Others',
                    'Other Restaurants, Hotels and Leisure':'Healthtech',
                    'Media and Information Services (B2B)':'Mobility',
                    'Therapeutic Devices':'Healthtech',
                    'Multimedia and Design Software':'Mobility',
                    'Laboratory Services (Healthcare)':'Healthtech',
                    'Internet Retail':'Healthtech',
                    'Software Development Applications':'Fintech',
                    'Machinery (B2B)':'Retail',
                    'Clinics/Outpatient Services':'Fintech',
                    'Financial Software':'Healthtech',
                    'Social/Platform Software':'Retail',
                    'Decision/Risk Analysis':'Healthtech',
                    'Media and Information Services (B2B)':'Mundo B2B',
                    'Application Specific Semiconductors':'Mobility',
                    'Diagnostic Equipment':'Healthtech',
                    'Marine':'Retail',
                    'Other Insurance':'Insuretech',
                    'Biotechnology':'Insuretech',
                    'Automotive':'Insuretech',
                    'Other Healthcare Technology Systems':'Insuretech',
                    'Communication Software':'Insuretech',
                    'Property and Casualty Insurance':'Insuretech',
                    'Elder and Disabled Care':'Insuretech',
                    'Business/Productivity Software':'Insuretech',
                    'Life and Health Insurance':'Insuretech',
                    'Insurance Brokers':'Insuretech',
                    'Logistics':'Deeptech',
                    'Life and Health Insurance':'Fintech',
                    'Energy Exploration':'Deeptech',
                    'Medical Records Systems':'Fintech',
                    'Real Estate Services (B2C)':'Mobility',
                    'Internet Software':'Deeptech',
                    'Energy Storage':'Mundo B2B',
                    'Medical Records Systems':'Healthtech',
                    'Software Development Applications':'Mobility',
                    'Software Development Applications':'Deeptech',
                    'Personal Products':'Retail',
                    'Communication Software':'Mundo B2B',
                    'Logistics':'Mundo B2B',
                    'Food Products':'Retail',
                    'Environmental Services (B2B)':'Deeptech',
                    'Business/Productivity Software':'Others',
                    'Social/Platform Software':'Fintech',
                    'Automation/Workflow Software':'Deeptech',
                    'Multimedia and Design Software':'Mundo B2B',
                    'Enterprise Systems (Healthcare)':'Healthtech',
                    'Special Purpose Acquisition Company (SPAC)':'Mundo B2B',
                    'Holding Companies':'Retail',
                    'Systems and Information Management':'Smart Cities',
                    'Environmental Services (B2B)':'Smart Cities',
                    'Business/Productivity Software':'Smart Cities',
                    'Other Commercial Services':'Healthtech',
                    'Educational Software':'Fintech',
                    'Business/Productivity Software':'Energy',
                    'Real Estate Services (B2C)':'Mundo B2B',
                    'Wireless Communications Equipment':'Smart Cities',
                    'Application Software':'Mundo B2B',
                    'Accounting, Audit and Tax Services (B2B)':'Mundo B2B',
                    'Internet Retail':'Mundo B2B',
                    'Social/Platform Software':'Mundo B2B',
                    'Other Media':'Others',
                    'Drug Delivery':'Healthtech',
                    'Alternative Energy Equipment':'Energy',
                    'Multi-line Insurance':'Insuretech',
                    'Network Management Software':'Mobility',
                    'IT Consulting and Outsourcing':'Mobility',
                    'Other Hardware':'Mobility',
                    'Road':'Mobility',
                    'Other Agriculture':'Agtech',
                    'Human Capital Services':'Fintech',
                    'Entertainment Software':'Fintech',
                    'Social/Platform Software':'Mobility',
                    'Database Software':'Mobility',
                    'Logistics':'Fintech',
                    'Application Software':'Healthtech',
                    'Electronics (B2C)':'Energy',
                    'Other Hardware':'Agtech',
                    'Pharmaceuticals':'Retail',
                    'Educational and Training Services (B2C)':'Mundo B2B',
                    'Network Management Software':'Retail',
                    'Other Services (B2C Non-Financial)':'Insuretech',
                    'Air':'Others',
                    'Human Capital Services':'Retail',
                    'Consulting Services (B2B)':'Retail',
                    'Communication Software':'Proptech',
                    'Information Services (B2C)':'Proptech',
                    'Elder and Disabled Care':'Healthtech',
                    'Automotive Insurance':'Mobility',
                    'Monitoring Equipment':'Healthtech',
                    'Other Commercial Banks':'Fintech',
                    'IT Consulting and Outsourcing':'Fintech',
                    'Electronic Equipment and Instruments':'Proptech',
                    'Systems and Information Management':'Mundo B2B',
                    'Network Management Software':'Fintech',
                    'Distributors (Healthcare)':'Retail',
                    'Consumer Finance':'Agtech',
                    'IT Consulting and Outsourcing':'Agtech',
                    'Multimedia and Design Software':'Proptech',
                    'Drug Discovery':'Healthtech',
                    'Automotive Insurance':'Insuretech',
                    'Construction and Engineering':'Proptech',
                    'Specialty Retail':'Fintech',
                    'Environmental Services (B2B)':'Fintech',
                    'Home Furnishings':'Proptech',
                    'Environmental Services (B2B)':'Energy',
                    'Monitoring Equipment':'Mobility',
                    'Information Services (B2C)':'Mundo B2B',
                    'Other Energy Services':'Smart Cities',
                    'Food Products':'Mundo B2B',
                    'Other Financial Services':'Retail',
                    'Building Products':'Proptech',
                    'Clinics/Outpatient Services':'Mundo B2B',
                    'Financial Software':'Deeptech',
                    'Other Services (B2C Non-Financial)':'Fintech',
                    'Aerospace and Defense':'Healthtech',
                    'Specialized Finance':'Mobility',
                    'IT Consulting and Outsourcing':'Others',
                    'Private Equity':'Others',
                    'Other Hardware':'Others',
                    'Monitoring Equipment':'Healthtech',
                    'Energy Production':'Energy',
                    'Software Development Applications':'Mundo B2B',
                    'Network Management Software':'Agtech',
                    'Other Restaurants, Hotels and Leisure':'Mundo B2B',
                    'Brokerage':'Proptech',
                    'Other Capital Markets/Institutions':'Mundo B2B',
                    'General Purpose Semiconductors':'Retail',
                    'Life and Health Insurance':'Deeptech',
                    'Brokerage':'Fintech',
                    'Other Healthcare Technology Systems':'Mundo B2B',
                    'Drug Discovery':'Mundo B2B',
                    'Human Capital Services':'Others',
                    'Electronics (B2C)':'Deeptech',
                    'Legal Services (B2B)':'Others',
                    'Electronic Equipment and Instruments':'Energy',
                    'Social Content':'Retail',
                    'Application Software':'Deeptech',
                    'Enterprise Systems (Healthcare)':'Retail',
                    'Biotechnology':'Energy',
                    'Personal Products':'Deeptech',
                    'Database Software':'Deeptech',
                    'Other Services (B2C Non-Financial)':'Energy',
                    'Internet Retail':'Deeptech',
                    'Automation/Workflow Software':'Fintech',
                    'Automotive':'Fintech',
                    'Education and Training Services (B2B)':'Retail',
                    'Financial Software':'Energy',
                    'Entertainment Software':'Others',
                    'Social/Platform Software':'Deeptech',
                    'Brokerage':'Mundo B2B',
                    'Other Hardware':'Mundo B2B',
                    'Other Devices and Supplies':'Retail',
                    'Other Commercial Services':'Retail',
                    'Marine':'Mobility',
                    'Educational and Training Services (B2C)':'Retail',
                    'Human Capital Services':'Healthtech',
                    'Communication Software':'Deeptech',
                    'National Banks':'Fintech',
                    'Road':'Mundo B2B',
                    'Software Development Applications':'Others',
                    'Medical Supplies':'Healthtech',
                    'Biotechnology':'Healthtech',
                    'Enterprise Systems (Healthcare)':'Mundo B2B',
                    'Aerospace and Defense':'Deeptech',
                    'Other Financial Services':'Deeptech',
                    'Entertainment Software':'Healthtech',
                    'Aerospace and Defense':'Energy',
                    'Clothing':'Deeptech',
                    'Specialty Chemicals':'Mobility',
                    'Clothing':'Proptech',
                    'Personal Products':'Proptech',
                    'Electronics (B2C)':'Healthtech',
                    'Special Purpose Acquisition Company (SPAC)':'Healthtech',
                    'Entertainment Software':'Retail',
                    'Other Hardware':'Deeptech',
                    'IT Consulting and Outsourcing':'Mundo B2B',
                    'Educational Software':'Mundo B2B',
                    'Surgical Devices':'Mundo B2B',
                    'Biotechnology':'Mundo B2B',
                    'Other Commercial Services':'Mundo B2B',
                    'Multi-line Insurance':'Mobility',
                    'Media and Information Services (B2B)':'Others',
                    'Human Capital Services':'Insuretech',
                    'Restaurants and Bars':'Retail',
                    'Specialty Retail':'Mundo B2B',
                    'Home Furnishings':'Mundo B2B',
                    'Systems and Information Management':'Fintech',
                    'Application Software':'Others',
                    'Holding Companies':'Mundo B2B',
                    'Consumer Finance':'Mobility',
                    'Paper Containers and Packaging':'Retail',
                    'Leisure Facilities':'Retail',
                    'Clothing':'Retail',
                    'Environmental Services (B2B)':'Mundo B2B'
                  }


    # Format transformation
    df["most_recent_deal_type_2"] = df["most_recent_deal_type_2"].replace(rename_dict1).astype("category")
    df["hq_country"] = df["hq_country"].replace(rename_dict2).astype("category")
    df["primary_industry_code"] = df["primary_industry_code"].replace(rename_dict3).astype("category")
    
    # 2. Feature Engineering & EDA
    # Startup age
    df['year_founded'] = pd.to_numeric(df['year_founded'])
    
    test_norm = df.copy()
    for feature_name in df.columns:     
        if feature_name not in list(df.select_dtypes(['category','object']).columns):
            #Fill na with mean
            test_norm[feature_name] = test_norm[feature_name].fillna(df_no_norm[feature_name].mean())
            #Normalize
            test_norm[feature_name] = test_norm[feature_name].astype(np.float64)
            max_val = df_no_norm[feature_name].max()
            min_val = df_no_norm[feature_name].min()
            test_norm[feature_name] = (test_norm[feature_name] - min_val) / (max_val - min_val)
    
    test_norm = test_norm.drop(columns = 'startup').values
    return df, test_norm